name = "ainews"
main = "src/worker.js"
compatibility_date = "2025-04-01"

routes = [
  { pattern = "ainews.hotloop.ai", custom_domain = true }
]

[assets]
directory = "./public"
not_found_handling = "single-page-application"
binding = "ASSETS"

[observability]
enabled = true

[[kv_namespaces]]
binding = "AINEWS"
id = "491c62f3f6a94b2185edc68a7bf0f30a"
